spring :
  datasource :
    url : jdbc:postgresql://localhost:5432/vale
    username : postgres
    password : Eleanor


#    initialization-mode : always

  jpa :
    hibernate:
      ddl-auto : update

